classdef TestEditorSelectionFormatting < matlab.unittest.TestCase
    %TESTEDITORSELECTIONFORMATTING Coverage for pure Editor selection planning.

    methods (Test)
        function testSelectionAtFileStartUsesLeadingBlock(testCase)
            documentText = sprintf([ ...
                'function y=foo(x)\n', ...
                'y=x+1;\n', ...
                'end\n', ...
                '\n', ...
                'z=3;\n']);

            request = MBeautifier.EditorSelectionFormatting.plan( ...
                documentText, [2, 1, 2, Inf], 'y=x+1;');

            testCase.verifyEqual(request.CodeBefore, '');
            testCase.verifyEqual(request.CodeToFormat, ...
                sprintf('function y=foo(x)\ny=x+1;\nend\n'));
            testCase.verifyEqual(request.CodeAfter, sprintf('\nz=3;\n'));
            testCase.verifyEqual(request.ExpandedSelection, [1, 1, 4, Inf]);
        end

        function testSelectionInMiddleUsesDelimitedBlock(testCase)
            documentText = sprintf([ ...
                'a=1;\n', ...
                '\n', ...
                'function y=foo(x)\n', ...
                'y=x+1;\n', ...
                'end\n', ...
                '\n', ...
                'c=3;\n']);

            request = MBeautifier.EditorSelectionFormatting.plan( ...
                documentText, [4, 1, 4, Inf], 'y=x+1;');

            testCase.verifyEqual(request.CodeBefore, sprintf('a=1;\n\n'));
            testCase.verifyEqual(request.CodeToFormat, ...
                sprintf('function y=foo(x)\ny=x+1;\nend\n'));
            testCase.verifyEqual(request.CodeAfter, sprintf('\nc=3;\n'));
            testCase.verifyEqual(request.ExpandedSelection, [2, 1, 6, Inf]);
        end

        function testSelectionAtFileEndUsesTrailingBlock(testCase)
            documentText = sprintf([ ...
                'a=1;\n', ...
                '\n', ...
                'function y=bar(x)\n', ...
                'y=x+2;\n', ...
                'end\n']);

            request = MBeautifier.EditorSelectionFormatting.plan( ...
                documentText, [4, 1, 4, Inf], 'y=x+2;');

            testCase.verifyEqual(request.CodeBefore, sprintf('a=1;\n\n'));
            testCase.verifyEqual(request.CodeToFormat, ...
                sprintf('function y=bar(x)\ny=x+2;\nend\n'));
            testCase.verifyEqual(request.CodeAfter, '');
            testCase.verifyEqual(request.ExpandedSelection, [2, 1, 5, Inf]);
        end

        function testSelectionWithoutBlankLinesUsesWholeDocument(testCase)
            documentText = sprintf([ ...
                'function y=foo(x)\n', ...
                'y=x+1;\n', ...
                'end\n', ...
                'function z=bar(x)\n', ...
                'z=x+2;\n', ...
                'end\n']);

            request = MBeautifier.EditorSelectionFormatting.plan( ...
                documentText, [5, 1, 5, Inf], 'z=x+2;');

            testCase.verifyEqual(request.CodeBefore, '');
            testCase.verifyEqual(request.CodeToFormat, documentText);
            testCase.verifyEqual(request.CodeAfter, '');
            testCase.verifyEqual(request.ExpandedSelection, [1, 1, 6, Inf]);
        end

        function testRebuildCombinesPlannedSegments(testCase)
            documentText = sprintf('a=1;\n\nb=2;\n\nc=3;\n');
            request = MBeautifier.EditorSelectionFormatting.plan( ...
                documentText, [3, 1, 3, Inf], 'b=2;');

            rebuiltText = MBeautifier.EditorSelectionFormatting.rebuild(request, sprintf('b = 2;\n'));

            testCase.verifyEqual(rebuiltText, sprintf('a=1;\n\nb = 2;\n\nc=3;\n'));
        end

        function testEmptySelectionErrors(testCase)
            documentText = sprintf('x=1;\n');

            testCase.verifyError( ...
                @() MBeautifier.EditorSelectionFormatting.plan(documentText, [1, 1, 1, 1], ''), ...
                'MBeautifier:NoSelectedEditorText');
        end
    end
end
