classdef TestContainerFormattingMatrix < matlab.unittest.TestCase
    %TESTCONTAINERFORMATTINGMATRIX Matrix coverage for container formatting.

    methods (Test)
        function testMatrixAndCellCommaInsertionHandlesUnaryOperators(testCase)
            input = sprintf([ ...
                'matrix = [1 2; -3 +4; ~mask values];\n', ...
                'cells = {foo bar; -baz +qux};\n']);
            expected = sprintf([ ...
                'matrix = [1, 2; -3, +4; ~mask, values];\n', ...
                'cells = {foo, bar; -baz, +qux};\n']);

            TestContainerFormattingMatrix.verifyStableExpectedFormatting( ...
                testCase, input, struct(), expected, 'containerUnaryComma.m');
        end

        function testIndexingAndFunctionCallsShareCurrentArithmeticSpacing(testCase)
            input = sprintf([ ...
                'idx = values(channel_range - 4);\n', ...
                'out = foo(channel_range - 4, values(2 + 3));\n']);
            expected = sprintf([ ...
                'idx = values(channel_range-4);\n', ...
                'out = foo(channel_range-4, values(2+3));\n']);
            overrides = struct('PreserveIndexExpressionSpacing', '0');

            TestContainerFormattingMatrix.verifyStableExpectedFormatting( ...
                testCase, input, overrides, expected, 'containerIndexCallSpacing.m');
        end

        function testKeywordContainersAreNotTreatedAsIndexing(testCase)
            input = sprintf([ ...
                'if(true)\n', ...
                'value=matrix (4);\n', ...
                'end\n']);
            expected = sprintf([ ...
                'if (true)\n', ...
                '    value = matrix(4);\n', ...
                'end\n']);
            overrides = struct('PreserveIndexExpressionSpacing', '0');

            TestContainerFormattingMatrix.verifyStableExpectedFormatting( ...
                testCase, input, overrides, expected, 'containerKeywordBoundary.m');
        end

        function testNestedMatrixCellAndCallContainersRemainStable(testCase)
            input = sprintf('nested = {foo([1 2], {bar baz}) [alpha beta]};\n');
            expected = sprintf('nested = {foo([1, 2], {bar, baz}), [alpha, beta]};\n');

            TestContainerFormattingMatrix.verifyStableExpectedFormatting( ...
                testCase, input, struct(), expected, 'containerNested.m');
        end

        function testCommaInsertionCanBeDisabledForMatrixAndCell(testCase)
            input = sprintf([ ...
                'matrix = [1 2; 3 4];\n', ...
                'cells = {''a'' ''b''; ''c'' ''d''};\n']);
            expected = sprintf([ ...
                'matrix = [1 2; 3 4];\n', ...
                'cells = {''a'' ''b''; ''c'' ''d''};\n']);
            overrides = struct( ...
                'AddCommasToMatrices', '0', ...
                'AddCommasToCellArrays', '0');

            TestContainerFormattingMatrix.verifyStableExpectedFormatting( ...
                testCase, input, overrides, expected, 'containerCommaDisabled.m');
        end

        function testInlineContinuationCommentsMoveBeforeNestedContainers(testCase)
            input = sprintf([ ...
                'values = {foo([1, ... %% matrix comment\n', ...
                '2]), ... %% call comment\n', ...
                '{''a'', ... %% cell comment\n', ...
                '''b''}};\n']);
            expected = sprintf([ ...
                '%% matrix comment\n', ...
                '%% call comment\n', ...
                '%% cell comment\n', ...
                'values = {foo([1, 2]), {''a'', ''b''}};\n']);
            overrides = struct( ...
                'InlineContinousLinesInMatrixes', '1', ...
                'InlineContinousLinesInCurlyBracket', '1');

            TestContainerFormattingMatrix.verifyStableExpectedFormatting( ...
                testCase, input, overrides, expected, 'containerInlineContinuation.m');
        end
    end

    methods (Static, Access = private)
        function verifyStableExpectedFormatting(testCase, input, overrides, expected, fileName)
            formatted = FormatterTestUtils.formatText(input, overrides);
            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));

            formattedAgain = FormatterTestUtils.formatText(formatted, overrides);
            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formattedAgain), ...
                FormatterTestUtils.normalizeText(formatted));

            TestContainerFormattingMatrix.verifyNoSyntaxIssues(testCase, formatted, fileName);
        end

        function verifyNoSyntaxIssues(testCase, text, fileName)
            path = FormatterTestUtils.writeTempTextFile(fileName, text);
            ids = FormatterTestUtils.checkcodeIds(path);
            syntaxIssueIds = {'SYNER', 'ENDCT', 'ENDCT1', 'ENDCT2', 'NOPAR'};
            hasSyntaxIssue = ismember(ids, syntaxIssueIds);

            testCase.verifyFalse(any(hasSyntaxIssue), ...
                sprintf('Unexpected syntax issues detected: %s', strjoin(ids(hasSyntaxIssue), ', ')));
        end
    end
end
