classdef TestIndentationRules < matlab.unittest.TestCase
    %TESTINDENTATIONRULES Focused coverage for indentation behavior.

    methods (Test)
        function testIfElseChainIndentation(testCase)
            input = sprintf([ ...
                'if cond\n', ...
                'x = 1;\n', ...
                'elseif otherCond\n', ...
                'y = 2;\n', ...
                'else\n', ...
                'z = 3;\n', ...
                'end\n']);

            expected = sprintf([ ...
                'if cond\n', ...
                '    x = 1;\n', ...
                'elseif otherCond\n', ...
                '    y = 2;\n', ...
                'else\n', ...
                '    z = 3;\n', ...
                'end\n']);
            actual = FormatterTestUtils.indentText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(actual), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testSwitchIndentation(testCase)
            input = sprintf([ ...
                'switch mode\n', ...
                'case 1\n', ...
                'x = 1;\n', ...
                'otherwise\n', ...
                'x = 0;\n', ...
                'end\n']);

            expected = sprintf([ ...
                'switch mode\n', ...
                '    case 1\n', ...
                '        x = 1;\n', ...
                '    otherwise\n', ...
                '        x = 0;\n', ...
                'end\n']);
            actual = FormatterTestUtils.indentText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(actual), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testTryCatchIndentation(testCase)
            input = sprintf([ ...
                'try\n', ...
                'runWork();\n', ...
                'catch ME\n', ...
                'handleError(ME);\n', ...
                'end\n']);

            expected = sprintf([ ...
                'try\n', ...
                '    runWork();\n', ...
                'catch ME\n', ...
                '    handleError(ME);\n', ...
                'end\n']);
            actual = FormatterTestUtils.indentText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(actual), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testNestedFunctionIndentation(testCase)
            input = sprintf([ ...
                'function topLevel()\n', ...
                'x = 1;\n', ...
                'function nested()\n', ...
                'y = x;\n', ...
                'end\n', ...
                'nested();\n', ...
                'end\n']);

            expected = sprintf([ ...
                'function topLevel()\n', ...
                'x = 1;\n', ...
                '    function nested()\n', ...
                '        y = x;\n', ...
                'end\n', ...
                '    nested();\n', ...
                'end\n']);

            actual = FormatterTestUtils.indentText(input, ...
                struct('Indentation_Strategy', 'nestedfunctions'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(actual), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testArgumentsBlockIndentation(testCase)
            input = sprintf([ ...
                'function y = foo(x, opts)\n', ...
                'arguments\n', ...
                'x (1,1) double\n', ...
                'opts.Name (1,1) string = ""\n', ...
                'end\n', ...
                'y = x;\n', ...
                'end\n']);

            expected = sprintf([ ...
                'function y = foo(x, opts)\n', ...
                'arguments\n', ...
                '    x (1,1) double\n', ...
                '    opts.Name (1,1) string = ""\n', ...
                'end\n', ...
                'y = x;\n', ...
                'end\n']);

            actual = FormatterTestUtils.indentText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(actual), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testContinuationLineIndentation(testCase)
            input = sprintf([ ...
                'value = firstPart + ...\n', ...
                'secondPart;\n']);

            expected = sprintf([ ...
                'value = firstPart + ...\n', ...
                '    secondPart;\n']);

            actual = FormatterTestUtils.indentText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(actual), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testMultilineMatrixDefaultIndentation(testCase)
            input = sprintf([ ...
                'function out = demo(options)\n', ...
                'arguments\n', ...
                'options.sceneKPairs (:, 2) double {mustBeFinite, mustBeInteger, mustBePositive} = [\n', ...
                '11, 5;\n', ...
                '4,  5;\n', ...
                '1,  3\n', ...
                ']\n', ...
                'end\n', ...
                'out = options.sceneKPairs;\n', ...
                'end\n']);

            expected = sprintf([ ...
                'function out = demo(options)\n', ...
                'arguments\n', ...
                '    options.sceneKPairs (:, 2) double {mustBeFinite, mustBeInteger, mustBePositive} = [\n', ...
                '        11, 5;\n', ...
                '        4, 5;\n', ...
                '        1, 3\n', ...
                '    ]\n', ...
                'end\n', ...
                'out = options.sceneKPairs;\n', ...
                'end\n']);

            actual = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(actual), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testNestedStructContinuationIndentation(testCase)
            input = sprintf([ ...
                'x = struct( ...\n', ...
                '''ga'', struct( ...\n', ...
                '''popSize'', double(resolved.popSize), ...\n', ...
                '''nElite'', double(resolved.nElite), ...\n', ...
                '''stop'', true));\n']);

            expected = sprintf([ ...
                'x = struct( ...\n', ...
                '    ''ga'', struct( ...\n', ...
                '        ''popSize'', double(resolved.popSize), ...\n', ...
                '        ''nElite'', double(resolved.nElite), ...\n', ...
                '        ''stop'', true));\n']);

            actual = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(actual), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testScriptLocalFunctionBodiesIndentByDefault(testCase)
            input = sprintf([ ...
                'x = 1;\n', ...
                'function val = getFieldValue(s, primary, secondary)\n', ...
                'if isfield(s, primary) && ~isempty(s.(primary))\n', ...
                'val = s.(primary);\n', ...
                'else\n', ...
                'val = [];\n', ...
                'end\n', ...
                'end\n']);

            expected = sprintf([ ...
                'x = 1;\n', ...
                'function val = getFieldValue(s, primary, secondary)\n', ...
                '    if isfield(s, primary) && ~isempty(s.(primary))\n', ...
                '        val = s.(primary);\n', ...
                '    else\n', ...
                '        val = [];\n', ...
                '    end\n', ...
                'end\n']);

            actual = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(actual), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testScriptLocalFunctionIndentationCanUseLegacyMode(testCase)
            input = sprintf([ ...
                'x = 1;\n', ...
                'function val = getFieldValue(s, primary, secondary)\n', ...
                'if isfield(s, primary) && ~isempty(s.(primary))\n', ...
                'val = s.(primary);\n', ...
                'else\n', ...
                'val = [];\n', ...
                'end\n', ...
                'end\n']);

            expected = sprintf([ ...
                'x = 1;\n', ...
                'function val = getFieldValue(s, primary, secondary)\n', ...
                'if isfield(s, primary) && ~isempty(s.(primary))\n', ...
                '    val = s.(primary);\n', ...
                'else\n', ...
                '    val = [];\n', ...
                'end\n', ...
                'end\n']);

            actual = FormatterTestUtils.formatText(input, ...
                struct('IndentScriptLocalFunctionBodies', '0'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(actual), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testBlankLinesCanRemainEmpty(testCase)
            input = sprintf([ ...
                'if cond\n', ...
                '\n', ...
                'x = 1;\n', ...
                'end\n']);

            expected = sprintf([ ...
                'if cond\n', ...
                '\n', ...
                '    x = 1;\n', ...
                'end\n']);

            actual = FormatterTestUtils.indentText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(actual), ...
                FormatterTestUtils.normalizeText(expected));
        end
    end
end
