classdef TestModernFormatting < matlab.unittest.TestCase
    %TESTMODERNFORMATTING Focused coverage for modern formatting behaviors.

    methods (Test)
        function testArgumentsBlockReadableStyle(testCase)
            input = sprintf([ ...
                'function y = foo(x, options)\n', ...
                'arguments\n', ...
                '    x (1, 1) double {mustBeFinite}\n', ...
                '    options.name (1, 1) string = ""\n', ...
                'end\n', ...
                'y = x;\n', ...
                'end\n']);

            formatted = FormatterTestUtils.formatText(input, ...
                struct('DeclarationSpacingStyle', 'Readable'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testArgumentsBlockPreserveStyle(testCase)
            input = sprintf([ ...
                'function y = foo(x, options)\n', ...
                'arguments\n', ...
                '    x   (1, 1) double   {mustBeFinite}\n', ...
                '    options.name    (1, 1) string   = ""\n', ...
                'end\n', ...
                'y = x;\n', ...
                'end\n']);

            formatted = FormatterTestUtils.formatText(input, ...
                struct('DeclarationSpacingStyle', 'Preserve'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testDefaultArgumentsDeclarationSpacingIsPreserved(testCase)
            input = sprintf([ ...
                'function y = foo(x, options)\n', ...
                'arguments\n', ...
                '    options.name (1, 1) string {mustBeNonzeroLengthText} = ...\n', ...
                '        "demo"\n', ...
                '    options.flags (1, :) double {mustBeFinite} = [1 2]\n', ...
                'end\n', ...
                'y = options.name;\n', ...
                'end\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testStatementBreakStrategyAlways(testCase)
            input = sprintf('clc; clear; close all;\n');
            expected = sprintf('clc;\nclear;\nclose all;\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('StatementBreakStrategy', 'Always'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testStatementBreakStrategyNever(testCase)
            input = sprintf('clc; clear; close all;\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('StatementBreakStrategy', 'Never'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testDefaultStatementBreakStrategyPreservesSetupChain(testCase)
            input = sprintf('clc; clear; close all;\n');

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testStatementBreakStrategyContextAwarePreservesCompactGuard(testCase)
            input = sprintf('if ~exist(outputDir, ''dir''); mkdir(outputDir); end\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('StatementBreakStrategy', 'ContextAware'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testStatementBreakStrategyContextAwareSplitsSetupChain(testCase)
            input = sprintf('clc; clear; close all;\n');
            expected = sprintf('clc;\nclear;\nclose all;\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('StatementBreakStrategy', 'ContextAware'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testStatementBreakStrategyContextAwarePreservesCompactTryCatch(testCase)
            input = sprintf('try; cleanup(); catch ME; disp(ME.message); end\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('StatementBreakStrategy', 'ContextAware'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testInlineCommentSpacingNormalize(testCase)
            input = sprintf('x = 1   %% comment\n');
            expected = sprintf('x = 1 %% comment\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('InlineCommentSpacingStrategy', 'Normalize'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testInlineCommentSpacingPreserve(testCase)
            input = sprintf('x = 1   %% comment\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('InlineCommentSpacingStrategy', 'Preserve'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testDefaultInlineCommentSpacingPreservesAlignment(testCase)
            input = sprintf([ ...
                'classdef Demo\n', ...
                'properties\n', ...
                'datatype            %% monocular or binocular\n', ...
                'sensorNETD          %% noise equivalent temperature difference\n', ...
                'end\n', ...
                'end\n']);
            expected = sprintf([ ...
                'classdef Demo\n', ...
                '    properties\n', ...
                '        datatype            %% monocular or binocular\n', ...
                '        sensorNETD          %% noise equivalent temperature difference\n', ...
                '    end\n', ...
                'end\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testDefaultSectionSpacingIsPreserved(testCase)
            input = sprintf([ ...
                'a = 1;\n', ...
                '\n', ...
                '\n', ...
                '%% init\n', ...
                'b = 2;\n', ...
                '\n', ...
                '%% run\n', ...
                'c = 3;\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testDefaultIndexExpressionSpacingIsPreserved(testCase)
            input = sprintf('heatcube(:, :, channel_range - 4) = heatcube(:, :, channel_range+1);\n');

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testIndexExpressionSpacingCanUseLegacyPadding(testCase)
            input = sprintf('heatcube(:, :, channel_range - 4) = heatcube(:, :, channel_range+1);\n');
            expected = sprintf('heatcube(:, :, channel_range-4) = heatcube(:, :, channel_range+1);\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('PreserveIndexExpressionSpacing', '0'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testArgumentsBlockReadableStyleWithValidatorsAndDefault(testCase)
            input = sprintf([ ...
                'function y = foo(x, options)\n', ...
                'arguments\n', ...
                '    x(1,1) double{mustBeFinite,mustBeReal}=""\n', ...
                '    options.name(1,1) string{mustBeNonzeroLengthText}="demo"\n', ...
                'end\n', ...
                'y = x;\n', ...
                'end\n']);

            expected = sprintf([ ...
                'function y = foo(x, options)\n', ...
                'arguments\n', ...
                '    x (1,1) double {mustBeFinite,mustBeReal} = ""\n', ...
                '    options.name (1,1) string {mustBeNonzeroLengthText} = "demo"\n', ...
                'end\n', ...
                'y = x;\n', ...
                'end\n']);

            formatted = FormatterTestUtils.formatText(input, ...
                struct('DeclarationSpacingStyle', 'Readable'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end
    end
end
