classdef TestEditorBehaviorMatrix < matlab.unittest.TestCase
    %TESTEDITORBEHAVIORMATRIX Locks MATLAB Editor integration behavior.

    methods (Test)
        function testSelectionAtFileStartFormatsLeadingBlockOnly(testCase)
            originalText = sprintf([ ...
                'function y=foo(x)\n', ...
                'y=x+1;\n', ...
                'end\n', ...
                '\n', ...
                'z=3;\n']);
            selectedBlock = sprintf('function y=foo(x)\ny=x+1;\nend\n');
            expectedText = sprintf('%s\nz=3;\n', ...
                FormatterTestUtils.formatText(selectedBlock));
            document = TestEditorBehaviorMatrix.openTemporaryDocument(testCase, ...
                'testSelectionAtFileStart.m', originalText);
            document.Selection = [2, 1, 2, Inf];
            document.makeActive();

            MBeautify.formatEditorSelection();

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(document.Text), ...
                FormatterTestUtils.normalizeText(expectedText));
        end

        function testSelectionInMiddleFormatsDelimitedBlockOnly(testCase)
            originalText = sprintf([ ...
                'a=1;\n', ...
                '\n', ...
                'function y=foo(x)\n', ...
                'y=x+1;\n', ...
                'end\n', ...
                '\n', ...
                'c=3;\n']);
            selectedBlock = sprintf('function y=foo(x)\ny=x+1;\nend\n');
            expectedText = sprintf('a=1;\n\n%s\nc=3;\n', ...
                FormatterTestUtils.formatText(selectedBlock));
            document = TestEditorBehaviorMatrix.openTemporaryDocument(testCase, ...
                'testSelectionInMiddle.m', originalText);
            document.Selection = [4, 1, 4, Inf];
            document.makeActive();

            MBeautify.formatEditorSelection();

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(document.Text), ...
                FormatterTestUtils.normalizeText(expectedText));
        end

        function testSelectionAtFileEndFormatsTrailingBlockOnly(testCase)
            originalText = sprintf([ ...
                'a=1;\n', ...
                '\n', ...
                'function y=bar(x)\n', ...
                'y=x+2;\n', ...
                'end\n']);
            selectedBlock = sprintf('function y=bar(x)\ny=x+2;\nend\n');
            expectedText = sprintf('a=1;\n\n%s', ...
                FormatterTestUtils.formatText(selectedBlock));
            document = TestEditorBehaviorMatrix.openTemporaryDocument(testCase, ...
                'testSelectionAtFileEnd.m', originalText);
            document.Selection = [4, 1, 4, Inf];
            document.makeActive();

            MBeautify.formatEditorSelection();

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(document.Text), ...
                FormatterTestUtils.normalizeText(expectedText));
        end

        function testSelectionWithoutBlankLinesFormatsWholeDocument(testCase)
            originalText = sprintf([ ...
                'function y=foo(x)\n', ...
                'y=x+1;\n', ...
                'end\n', ...
                'function z=bar(x)\n', ...
                'z=x+2;\n', ...
                'end\n']);
            expectedText = FormatterTestUtils.formatText(originalText);
            document = TestEditorBehaviorMatrix.openTemporaryDocument(testCase, ...
                'testSelectionWithoutBlankLines.m', originalText);
            document.Selection = [5, 1, 5, Inf];
            document.makeActive();

            MBeautify.formatEditorSelection();

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(document.Text), ...
                FormatterTestUtils.normalizeText(expectedText));
        end

        function testFormatEditorSelectionErrorsWhenSelectionIsEmpty(testCase)
            originalText = sprintf('x=1;\n');
            document = TestEditorBehaviorMatrix.openTemporaryDocument(testCase, ...
                'testEmptySelection.m', originalText);
            document.Selection = [1, 1, 1, 1];
            document.makeActive();

            testCase.verifyError(@() MBeautify.formatEditorSelection(), ...
                'MBeautifier:NoSelectedEditorText');
        end

        function testFormatCurrentEditorPageWithoutSaveLeavesFileUnchanged(testCase)
            originalText = sprintf('function y=foo(x)\ny=x+1;\nend\n');
            document = TestEditorBehaviorMatrix.openTemporaryDocument(testCase, ...
                'testFormatWithoutSave.m', originalText);
            path = document.Filename;
            expectedText = FormatterTestUtils.formatText(originalText);
            document.makeActive();

            MBeautify.formatCurrentEditorPage(false);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(document.Text), ...
                FormatterTestUtils.normalizeText(expectedText));
            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(FormatterTestUtils.readText(path)), ...
                FormatterTestUtils.normalizeText(originalText));
        end

        function testFormatCurrentEditorPageWithSaveWritesFile(testCase)
            originalText = sprintf('function y=foo(x)\ny=x+1;\nend\n');
            document = TestEditorBehaviorMatrix.openTemporaryDocument(testCase, ...
                'testFormatWithSave.m', originalText);
            path = document.Filename;
            expectedText = FormatterTestUtils.formatText(originalText);
            document.makeActive();

            MBeautify.formatCurrentEditorPage(true);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(document.Text), ...
                FormatterTestUtils.normalizeText(expectedText));
            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(FormatterTestUtils.readText(path)), ...
                FormatterTestUtils.normalizeText(expectedText));
        end
    end

    methods (Static, Access = private)
        function document = openTemporaryDocument(testCase, fileName, text)
            path = FormatterTestUtils.writeTempTextFile(fileName, text);
            document = matlab.desktop.editor.openDocument(path);

            testCase.addTeardown(@() TestEditorBehaviorMatrix.closeDocumentIfOpen(document));
            testCase.addTeardown(@() TestEditorBehaviorMatrix.deleteIfExists(path));
        end

        function closeDocumentIfOpen(document)
            if ~isempty(document) && isvalid(document)
                document.close();
                drawnow();
            end
        end

        function deleteIfExists(path)
            if exist(path, 'file') == 2
                delete(path);
            end
        end
    end
end
