classdef TestModernFormatting < matlab.unittest.TestCase
    %TESTMODERNFORMATTING Focused coverage for modern formatting behaviors.

    methods (Test)
        function testArgumentsBlockReadableStyle(testCase)
            input = sprintf([ ...
                'function y = foo(x, options)\n', ...
                'arguments\n', ...
                '    x (1, 1) double {mustBeFinite}\n', ...
                '    options.name (1, 1) string = ""\n', ...
                'end\n', ...
                'y = x;\n', ...
                'end\n']);

            formatted = FormatterTestUtils.formatText(input, ...
                struct('DeclarationSpacingStyle', 'Readable'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testArgumentsBlockPreserveStyle(testCase)
            input = sprintf([ ...
                'function y = foo(x, options)\n', ...
                'arguments\n', ...
                '    x   (1, 1) double   {mustBeFinite}\n', ...
                '    options.name    (1, 1) string   = ""\n', ...
                'end\n', ...
                'y = x;\n', ...
                'end\n']);

            formatted = FormatterTestUtils.formatText(input, ...
                struct('DeclarationSpacingStyle', 'Preserve'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testStatementBreakStrategyAlways(testCase)
            input = sprintf('clc; clear; close all;\n');
            expected = sprintf('clc;\nclear;\nclose all;\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('StatementBreakStrategy', 'Always'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testStatementBreakStrategyNever(testCase)
            input = sprintf('clc; clear; close all;\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('StatementBreakStrategy', 'Never'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testStatementBreakStrategyContextAwarePreservesCompactGuard(testCase)
            input = sprintf('if ~exist(outputDir, ''dir''); mkdir(outputDir); end\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('StatementBreakStrategy', 'ContextAware'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testStatementBreakStrategyContextAwareSplitsSetupChain(testCase)
            input = sprintf('clc; clear; close all;\n');
            expected = sprintf('clc;\nclear;\nclose all;\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('StatementBreakStrategy', 'ContextAware'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testInlineCommentSpacingNormalize(testCase)
            input = sprintf('x = 1   %% comment\n');
            expected = sprintf('x = 1 %% comment\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('InlineCommentSpacingStrategy', 'Normalize'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testInlineCommentSpacingPreserve(testCase)
            input = sprintf('x = 1   %% comment\n');

            formatted = FormatterTestUtils.formatText(input, ...
                struct('InlineCommentSpacingStrategy', 'Preserve'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end
    end
end
