classdef TestFormatterContinuationBehavior < matlab.unittest.TestCase
    %TESTFORMATTERCONTINUATIONBEHAVIOR Focused coverage for continuation handling.

    methods (Test)
        function testMatrixContinuationWithInlineCommentsRemainsStable(testCase)
            input = sprintf([ ...
                'a = [1, a ... %% 111\n', ...
                '.* 2, ... %% 222\n', ...
                '123, 4 - ...\n', ...
                '    5] %% 333\n']);
            expected = sprintf([ ...
                'a = [1, a ... %% 111\n', ...
                '    .* 2, ... %% 222\n', ...
                '    123, 4 - ...\n', ...
                '    5] %% 333\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testCellContinuationWithInlineCommentsRemainsStable(testCase)
            input = sprintf([ ...
                'a = {'''', ... %% hello\n', ...
                '1, 4 + ... %%hello2\n', ...
                '2} %% hello3\n']);
            expected = sprintf([ ...
                'a = {'''', ... %% hello\n', ...
                '    1, 4 + ... %%hello2\n', ...
                '    2} %% hello3\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testFunctionCallContinuationKeepsArithmeticSpacing(testCase)
            input = sprintf([ ...
                'result = foo(1 + ...\n', ...
                '2);\n']);
            expected = sprintf([ ...
                'result = foo(1+ ...\n', ...
                '    2);\n']);

            formatted = FormatterTestUtils.formatText(input, ...
                struct('PreserveIndexExpressionSpacing', '0'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end

        function testNestedFunctionCallContinuationUsesSingleIndent(testCase)
            input = sprintf([ ...
                'gt_eMap = importdata(fullfile(groundtruth_dir, "eMap", ...\n', ...
                '    sprintf("eMap_%%s.mat", heatcube_num)));\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testErrorContinuationStringKeepsIndentation(testCase)
            input = sprintf([ ...
                'error(''runBandselectionComparisonExperiment:EmptyGASeedList'', ...\n', ...
                '    ''gaSeedList must contain at least one random seed.'');\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testTopLevelContinuationKeepsSingleIndent(testCase)
            input = sprintf([ ...
                'value = 1 + ...\n', ...
                '    2 + ...\n', ...
                '    3;\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testCloseThenOpenContinuationKeepsNestedIndent(testCase)
            input = sprintf([ ...
                'result = outer(inner(first( ...\n', ...
                '    value ...\n', ...
                '    )), other( ...\n', ...
                '        next));\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testBalancedCallBeforeCloseDoesNotAddNestedIndent(testCase)
            input = sprintf([ ...
                'result = outer(inner( ...\n', ...
                '    foo(bar)), ...\n', ...
                '    next);\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testMultilineArgumentsMatrixDefaultDoesNotAppendContinuation(testCase)
            input = sprintf([ ...
                'function out = demo(options)\n', ...
                'arguments\n', ...
                '    options.sceneKPairs (:, 2) double {mustBeFinite, mustBeInteger} = [\n', ...
                '        11, 5;\n', ...
                '        4,  5;\n', ...
                '        1,  3\n', ...
                '    ]\n', ...
                'end\n', ...
                'out = options.sceneKPairs;\n', ...
                'end\n']);
            expected = sprintf([ ...
                'function out = demo(options)\n', ...
                'arguments\n', ...
                '    options.sceneKPairs (:, 2) double {mustBeFinite, mustBeInteger} = [\n', ...
                '        11, 5;\n', ...
                '        4, 5;\n', ...
                '        1, 3\n', ...
                '    ]\n', ...
                'end\n', ...
                'out = options.sceneKPairs;\n', ...
                'end\n']);

            formatted = FormatterTestUtils.formatText(input, ...
                struct('PreserveIndexExpressionSpacing', '0'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
            testCase.verifyEmpty(regexp(formatted, '\[; \.\.\.', 'once'));
        end

        function testAutoAppendContinuationMarkersCanRestoreLegacyBehavior(testCase)
            input = sprintf([ ...
                'values = [\n', ...
                '    1, 2\n', ...
                ']\n']);

            formatted = FormatterTestUtils.formatText(input, ...
                struct('AutoAppendContinuationMarkers', '1'));

            testCase.verifyNotEmpty(regexp(formatted, '\[; \.\.\.', 'once'));
        end

        function testInlineContinuousLinesWorksForPreservedArgumentsDeclaration(testCase)
            input = sprintf([ ...
                'function y = demo(options)\n', ...
                'arguments\n', ...
                '    options.name (1, 1) string = ...\n', ...
                '        "demo"\n', ...
                'end\n', ...
                'y = options.name;\n', ...
                'end\n']);

            formatted = FormatterTestUtils.formatText(input, ...
                struct('DeclarationSpacingStyle', 'Preserve', ...
                'InlineContinousLines', '1'));

            testCase.verifyEmpty(regexp(formatted, '\.\.\.', 'once'));
        end
    end
end
