classdef TestEditorBehaviorMatrix < matlab.unittest.TestCase
    %TESTEDITORBEHAVIORMATRIX Locks MATLAB Editor integration behavior.

    methods (Test)
        function testSelectionAtFileStartFormatsLeadingBlockOnly(testCase)
            originalText = sprintf([ ...
                'function y=foo(x)\n', ...
                'y=x+1;\n', ...
                'end\n', ...
                '\n', ...
                'z=3;\n']);
            selectedBlock = sprintf('function y=foo(x)\ny=x+1;\nend\n');
            expectedText = sprintf('%s\nz=3;\n', ...
                FormatterTestUtils.formatText(selectedBlock));
            document = EditorTestUtils.openTemporaryDocument(testCase, ...
                'testSelectionAtFileStart.m', originalText);
            MBeautifier.DesktopAdapter.setSelection(document, [2, 1, 2, Inf]);
            MBeautifier.DesktopAdapter.activateDocument(document);

            MBeautify.formatEditorSelection();

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(MBeautifier.DesktopAdapter.getText(document)), ...
                FormatterTestUtils.normalizeText(expectedText));
        end

        function testSelectionInMiddleFormatsDelimitedBlockOnly(testCase)
            originalText = sprintf([ ...
                'a=1;\n', ...
                '\n', ...
                'function y=foo(x)\n', ...
                'y=x+1;\n', ...
                'end\n', ...
                '\n', ...
                'c=3;\n']);
            selectedBlock = sprintf('function y=foo(x)\ny=x+1;\nend\n');
            expectedText = sprintf('a=1;\n\n%s\nc=3;\n', ...
                FormatterTestUtils.formatText(selectedBlock));
            document = EditorTestUtils.openTemporaryDocument(testCase, ...
                'testSelectionInMiddle.m', originalText);
            MBeautifier.DesktopAdapter.setSelection(document, [4, 1, 4, Inf]);
            MBeautifier.DesktopAdapter.activateDocument(document);

            MBeautify.formatEditorSelection();

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(MBeautifier.DesktopAdapter.getText(document)), ...
                FormatterTestUtils.normalizeText(expectedText));
        end

        function testSelectionAtFileEndFormatsTrailingBlockOnly(testCase)
            originalText = sprintf([ ...
                'a=1;\n', ...
                '\n', ...
                'function y=bar(x)\n', ...
                'y=x+2;\n', ...
                'end\n']);
            selectedBlock = sprintf('function y=bar(x)\ny=x+2;\nend\n');
            expectedText = sprintf('a=1;\n\n%s', ...
                FormatterTestUtils.formatText(selectedBlock));
            document = EditorTestUtils.openTemporaryDocument(testCase, ...
                'testSelectionAtFileEnd.m', originalText);
            MBeautifier.DesktopAdapter.setSelection(document, [4, 1, 4, Inf]);
            MBeautifier.DesktopAdapter.activateDocument(document);

            MBeautify.formatEditorSelection();

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(MBeautifier.DesktopAdapter.getText(document)), ...
                FormatterTestUtils.normalizeText(expectedText));
        end

        function testSelectionWithoutBlankLinesFormatsWholeDocument(testCase)
            originalText = sprintf([ ...
                'function y=foo(x)\n', ...
                'y=x+1;\n', ...
                'end\n', ...
                'function z=bar(x)\n', ...
                'z=x+2;\n', ...
                'end\n']);
            expectedText = FormatterTestUtils.formatText(originalText);
            document = EditorTestUtils.openTemporaryDocument(testCase, ...
                'testSelectionWithoutBlankLines.m', originalText);
            MBeautifier.DesktopAdapter.setSelection(document, [5, 1, 5, Inf]);
            MBeautifier.DesktopAdapter.activateDocument(document);

            MBeautify.formatEditorSelection();

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(MBeautifier.DesktopAdapter.getText(document)), ...
                FormatterTestUtils.normalizeText(expectedText));
        end

        function testFormatEditorSelectionErrorsWhenSelectionIsEmpty(testCase)
            originalText = sprintf('x=1;\n');
            document = EditorTestUtils.openTemporaryDocument(testCase, ...
                'testEmptySelection.m', originalText);
            MBeautifier.DesktopAdapter.setSelection(document, [1, 1, 1, 1]);
            MBeautifier.DesktopAdapter.activateDocument(document);

            testCase.verifyError(@() MBeautify.formatEditorSelection(), ...
                'MBeautifier:NoSelectedEditorText');
        end

        function testFormatCurrentEditorPageWithoutSaveLeavesFileUnchanged(testCase)
            originalText = sprintf('function y=foo(x)\ny=x+1;\nend\n');
            document = EditorTestUtils.openTemporaryDocument(testCase, ...
                'testFormatWithoutSave.m', originalText);
            path = MBeautifier.DesktopAdapter.getFilename(document);
            expectedText = FormatterTestUtils.formatText(originalText);
            MBeautifier.DesktopAdapter.activateDocument(document);

            MBeautify.formatCurrentEditorPage(false);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(MBeautifier.DesktopAdapter.getText(document)), ...
                FormatterTestUtils.normalizeText(expectedText));
            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(FormatterTestUtils.readText(path)), ...
                FormatterTestUtils.normalizeText(originalText));
        end

        function testFormatCurrentEditorPageWithSaveWritesFile(testCase)
            originalText = sprintf('function y=foo(x)\ny=x+1;\nend\n');
            document = EditorTestUtils.openTemporaryDocument(testCase, ...
                'testFormatWithSave.m', originalText);
            path = MBeautifier.DesktopAdapter.getFilename(document);
            expectedText = FormatterTestUtils.formatText(originalText);
            MBeautifier.DesktopAdapter.activateDocument(document);

            MBeautify.formatCurrentEditorPage(true);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(MBeautifier.DesktopAdapter.getText(document)), ...
                FormatterTestUtils.normalizeText(expectedText));
            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(FormatterTestUtils.readText(path)), ...
                FormatterTestUtils.normalizeText(expectedText));
        end
    end

end
