classdef TestFormatterIdempotence < matlab.unittest.TestCase
    %TESTFORMATTERIDEMPOTENCE Expanded idempotence coverage for key fixtures.

    methods (Test)
        function testIssue0035FixtureIsIdempotent(testCase)
            input = FormatterTestUtils.readFixture(fullfile('issues', ...
                'issue_0035_function_call_arithmetic_spacing.m'));

            onceFormatted = FormatterTestUtils.formatText(input);
            twiceFormatted = FormatterTestUtils.formatText(onceFormatted);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(twiceFormatted), ...
                FormatterTestUtils.normalizeText(onceFormatted));
        end

        function testModernContextAwareFormattingIsIdempotent(testCase)
            input = sprintf('clc; clear; close all;\n');

            onceFormatted = FormatterTestUtils.formatText(input, ...
                struct('StatementBreakStrategy', 'ContextAware'));
            twiceFormatted = FormatterTestUtils.formatText(onceFormatted, ...
                struct('StatementBreakStrategy', 'ContextAware'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(twiceFormatted), ...
                FormatterTestUtils.normalizeText(onceFormatted));
        end

        function testModernArgumentsFormattingIsIdempotent(testCase)
            input = sprintf([ ...
                'function y = foo(x, options)\n', ...
                'arguments\n', ...
                '    x(1,1) double{mustBeFinite,mustBeReal}=""\n', ...
                '    options.name(1,1) string{mustBeNonzeroLengthText}="demo"\n', ...
                'end\n', ...
                'y = x;\n', ...
                'end\n']);

            onceFormatted = FormatterTestUtils.formatText(input, ...
                struct('DeclarationSpacingStyle', 'Readable'));
            twiceFormatted = FormatterTestUtils.formatText(onceFormatted, ...
                struct('DeclarationSpacingStyle', 'Readable'));

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(twiceFormatted), ...
                FormatterTestUtils.normalizeText(onceFormatted));
        end
    end
end
