classdef TestFormatterCrossBehaviorMatrix < matlab.unittest.TestCase
    %TESTFORMATTERCROSSBEHAVIORMATRIX Cross-behavior formatter regression coverage.

    methods (Test)
        function testDirectiveRegionPreservesRawTextAndFormattingResumes(testCase)
            input = sprintf([ ...
                'x=1;\n', ...
                '%% MBeautifierDirective:Format:off\n', ...
                'y=1+2;   %% keep raw\n', ...
                's = "100%% done";\n', ...
                '%% MBD:Format:on\n', ...
                'z=3+4;\n']);
            expected = sprintf([ ...
                'x = 1;\n', ...
                '%% MBeautifierDirective:Format:off\n', ...
                'y=1+2;   %% keep raw\n', ...
                's = "100%% done";\n', ...
                '%% MBD:Format:on\n', ...
                'z = 3 + 4;\n']);

            TestFormatterCrossBehaviorMatrix.verifyStableExpectedFormatting( ...
                testCase, input, struct(), expected, 'directiveBoundary.m');
        end

        function testInlineContainerContinuationOptionsMoveCommentsBeforeCode(testCase)
            matrixInput = sprintf([ ...
                'values = [1, ... %% first\n', ...
                '2, ... %% second\n', ...
                '3];\n']);
            matrixExpected = sprintf([ ...
                '%% first\n', ...
                '%% second\n', ...
                'values = [1, 2, 3];\n']);
            TestFormatterCrossBehaviorMatrix.verifyStableExpectedFormatting( ...
                testCase, matrixInput, struct('InlineContinousLinesInMatrixes', '1'), ...
                matrixExpected, 'inlineMatrixContinuation.m');

            cellInput = sprintf([ ...
                'values = {''a'', ... %% first\n', ...
                '''b'', ... %% second\n', ...
                '''c''};\n']);
            cellExpected = sprintf([ ...
                '%% first\n', ...
                '%% second\n', ...
                'values = {''a'', ''b'', ''c''};\n']);
            TestFormatterCrossBehaviorMatrix.verifyStableExpectedFormatting( ...
                testCase, cellInput, struct('InlineContinousLinesInCurlyBracket', '1'), ...
                cellExpected, 'inlineCellContinuation.m');
        end

        function testCommaAndIndexSpacingOptionsShareOneScenario(testCase)
            input = sprintf([ ...
                'idx = values(channel_range - 4);\n', ...
                'matrix = [1 2; 3 4];\n', ...
                'cells = {''a'' ''b''};\n']);
            expected = sprintf([ ...
                'idx = values(channel_range-4);\n', ...
                'matrix = [1, 2; 3, 4];\n', ...
                'cells = {''a'', ''b''};\n']);
            overrides = struct( ...
                'PreserveIndexExpressionSpacing', '0', ...
                'AddCommasToMatrices', '1', ...
                'AddCommasToCellArrays', '1');

            TestFormatterCrossBehaviorMatrix.verifyStableExpectedFormatting( ...
                testCase, input, overrides, expected, 'commaIndexSpacing.m');
        end

        function testNewlineConfigurationCombinesWithSectionSpacing(testCase)
            input = sprintf([ ...
                '\n\n', ...
                'a = 1;\n', ...
                '\n\n\n', ...
                '%% section\n', ...
                'b = 2;\n', ...
                '\n\n']);
            expected = sprintf([ ...
                '\n', ...
                'a = 1;\n', ...
                '\n', ...
                '%% section\n', ...
                'b = 2;\n', ...
                '\n']);
            overrides = struct( ...
                'StartingNewlineCount', '1', ...
                'EndingNewlineCount', '2', ...
                'MaximalNewLines', '1', ...
                'SectionPrecedingNewlineCount', '1', ...
                'SectionTrailingNewlineCount', '1');

            TestFormatterCrossBehaviorMatrix.verifyStableExpectedFormatting( ...
                testCase, input, overrides, expected, 'newlineSectionSpacing.m');
        end

        function testNestedCallContinuationKeepsStringCommentAndTransposeBoundaries(testCase)
            input = sprintf([ ...
                'function y = crossBoundary(a)\n', ...
                'name = "a %% b";\n', ...
                'label = ''can''''t %% comment'';\n', ...
                'y = foo(a'' + ... %% transpose continuation\n', ...
                '1, [1, ... %% matrix\n', ...
                '2], {''a'', ... %% cell\n', ...
                '''b''}); %% trailing\n', ...
                'end\n']);
            expected = sprintf([ ...
                'function y = crossBoundary(a)\n', ...
                'name = "a %% b";\n', ...
                'label = ''can''''t %% comment'';\n', ...
                'y = foo(a''+ ... %% transpose continuation\n', ...
                '    1, [1, ... %% matrix\n', ...
                '        2], {''a'', ... %% cell\n', ...
                '        ''b''}); %% trailing\n', ...
                'end\n']);

            TestFormatterCrossBehaviorMatrix.verifyStableExpectedFormatting( ...
                testCase, input, struct('PreserveIndexExpressionSpacing', '0'), ...
                expected, 'crossBoundary.m');
        end
    end

    methods (Static, Access = private)
        function verifyStableExpectedFormatting(testCase, input, overrides, expected, fileName)
            formatted = FormatterTestUtils.formatText(input, overrides);
            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));

            formattedAgain = FormatterTestUtils.formatText(formatted, overrides);
            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formattedAgain), ...
                FormatterTestUtils.normalizeText(formatted));

            TestFormatterCrossBehaviorMatrix.verifyNoSyntaxIssues(testCase, formatted, fileName);
        end

        function verifyNoSyntaxIssues(testCase, text, fileName)
            path = FormatterTestUtils.writeTempTextFile(fileName, text);
            ids = FormatterTestUtils.checkcodeIds(path);
            syntaxIssueIds = {'SYNER', 'ENDCT', 'ENDCT1', 'ENDCT2', 'NOPAR'};
            hasSyntaxIssue = ismember(ids, syntaxIssueIds);

            testCase.verifyFalse(any(hasSyntaxIssue), ...
                sprintf('Unexpected syntax issues detected: %s', strjoin(ids(hasSyntaxIssue), ', ')));
        end
    end
end
