classdef TestFormatterContinuationBehavior < matlab.unittest.TestCase
    %TESTFORMATTERCONTINUATIONBEHAVIOR Focused coverage for continuation handling.

    methods (Test)
        function testMatrixContinuationWithInlineCommentsRemainsStable(testCase)
            input = sprintf([ ...
                'a = [1, a ... %% 111\n', ...
                '.* 2, ... %% 222\n', ...
                '123, 4 - ...\n', ...
                '    5] %% 333\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testCellContinuationWithInlineCommentsRemainsStable(testCase)
            input = sprintf([ ...
                'a = {'''', ... %% hello\n', ...
                '1, 4 + ... %%hello2\n', ...
                '2} %% hello3\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(input));
        end

        function testFunctionCallContinuationKeepsArithmeticSpacing(testCase)
            input = sprintf([ ...
                'result = foo(1 + ...\n', ...
                '2);\n']);
            expected = sprintf([ ...
                'result = foo(1+ ...\n', ...
                '    2);\n']);

            formatted = FormatterTestUtils.formatText(input);

            testCase.verifyEqual( ...
                FormatterTestUtils.normalizeText(formatted), ...
                FormatterTestUtils.normalizeText(expected));
        end
    end
end
